# Generated by Django 4.1.3 on 2024-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("priority", models.IntegerField()),
                ("description", models.TextField()),
                ("comp_score", models.IntegerField()),
                (
                    "prior_concepts",
                    models.ManyToManyField(
                        related_name="prerequisites", to="api.concept"
                    ),
                ),
                (
                    "related_concepts",
                    models.ManyToManyField(related_name="related_to", to="api.concept"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuperConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "concepts",
                    models.ManyToManyField(
                        related_name="super_concepts", to="api.concept"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("link", models.URLField()),
                (
                    "concepts",
                    models.ManyToManyField(related_name="articles", to="api.concept"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
